```{r}
install.packages("ggplot2")
install.packages("olsrr")
```

```{r}
library(readr)
datasetfull <- read_csv("insurance.csv")
```
```{r}
keep<-c('age','bmi','children','charges')
num_data<-subset(datasetfull, select=keep)
cor(num_data)
```
```{r}
pairs(~age+bmi+children+charges,data=datasetfull)
```

```{r}
ggplot(data = datasetfull, aes(x = sex, y = charges)) + geom_point()
```
```{r}
ggplot(data = datasetfull, aes(sex))+geom_histogram(stat = "count", fill = c("orange", "blue"))
```

```{r}

ggplot(data = datasetfull, aes(x = as.factor(children), y = charges)) + geom_boxplot() + labs(x = "Number of Children")
```

```{r}
ggplot(data = datasetfull, aes(x = smoker, y = charges)) + geom_boxplot()
```

```{r}
ggplot(data = datasetfull, aes(x = region, y = charges)) + geom_boxplot()
```
```{r}
bmi_category <- cut(datasetfull$bmi, c(0, 18.5, 24.9, 29.9, 10000), labels = c("Underweight","Healthy weight","Overweight","Obese"), right = FALSE)
bmi_category <- data.frame((bmi_category))
bmidata <- cbind(charge = datasetfull$charges, bmi = bmi_category)
colnames(bmidata) <- c("charge", "bmi")
ggplot(data = bmidata, aes(x = bmi, y = charge)) + geom_boxplot()
```
```{r}
age_range <- data.frame(ifelse(datasetfull$age < 20, "Minor", "Adult"))
agedata <- cbind(datasetfull$charges, age_range)
colnames(agedata) <- c("charge", "age")
ggplot(data = agedata, aes(x = age, y = charge)) + geom_boxplot()
```
```{r}
  ggplot(agedata, aes(x = age))+geom_histogram(stat="count", fill = c("orange", "blue"))
```


```{r}
datasetfull[nrow(datasetfull) + 1,] <- list(22,"female",23.71,0,"no","northeast",5503.7768)
```

```{r}
unique(datasetfull$region)
```

```{r}
datasetfull$sex<-as.factor(datasetfull$sex)
datasetfull$region<-as.factor(datasetfull$region)
datasetfull$smoker<-as.factor(datasetfull$smoker)
datasetfull$sex_male <- ifelse(datasetfull$sex == "male", 1, 0)
datasetfull$sex_female <- ifelse(datasetfull$sex == "female", 1, 0)
datasetfull$region_southwest <- ifelse(datasetfull$region == "southwest", 1, 0)
datasetfull$region_southeast <- ifelse(datasetfull$region == "southeast", 1, 0)
datasetfull$region_northwest <- ifelse(datasetfull$region == "northwest", 1, 0)
datasetfull$region_northeast <- ifelse(datasetfull$region == "northeast", 1, 0)
datasetfull$smoker_yes <- ifelse(datasetfull$smoker == "yes", 1, 0)
datasetfull$smoker_no <- ifelse(datasetfull$smoker == "no", 1, 0)
datasetfull <- subset(datasetfull, select = -c(sex, region, smoker))
```



```{r}
fullmodel1=lm(charges~region_southwest+region_southeast+region_northwest+region_northeast+age+bmi+children+sex_male+smoker_yes+sex_female+smoker_no,data=datasetfull)
step1=step(fullmodel1,direction="backward")
summary(step1)
```

```{r}
fullmodel2=lm(charges~region_southwest+region_southeast+region_northwest+region_northeast+age+bmi+children+sex_male*smoker_yes+sex_female*smoker_no+sex_male*smoker_no+sex_male*smoker_yes,data=datasetfull)
step2=step(fullmodel2,direction="backward")
summary(step2)
```
```{r}
anova(step1,step2)
```
```{r}
plot(step2)
# Residuals vs Fitted:
# Looking at the Residuals vs Fitted plot, we can see that the red line is approximately flat, which means that the mean of error is approximately equal to 0.
# Normal Q-Q:
# The residuals are approximately matched to the diagonal line, which means that the residuals are roughly normally distributed. And we can see that both the upper and lower tail are ‘heavier’ (have larger values) than what we would expect under the gauss-markov assumptions. 
# Scale-Location:
# Looking at the Scale-Location plot, we can see that the red line is approximately flat, which means that there is no indication of having non-constant variance.
# Residuals vs Leverage:
# The Residuals vs Leverage plot indicate that there is no evidence of outliers because the “Cook’s distance” dashed curves don’t even appear on the plot. And there exists some leverage points: 1301, 578, 544.
```

```{r}
install.packages("MPV")
install.packages("faraway")
library(MPV)
library(faraway)
vif(step2)
# As for the multicolinearity, since all the attributes' vif are less than 10, we can conclude that these variables are independent.
```