---
title: "STAT3340-proj"
author: "Yurunyun Wang"
date: "12/5/2020"
output: pdf_document
---

```{r}
datasetfull <- read.csv(file = '~/Desktop/insurance.csv')
#Add one more data to the dataset
datasetfull[nrow(datasetfull) + 1,] = c(22,"female",23.71,0,"no","northeast",5503.7768)
datasetfull
```

```{r}
#install.packages("tidyverse")
library(tidyverse)
ggplot(data = datasetfull, aes(x = sex, y = charges)) + geom_point()
```

```{r}
ggplot(data = datasetfull, aes(x = children, y = charges)) + geom_point()
```

```{r}
ggplot(data = datasetfull, aes(x = smoker, y = charges)) + geom_point()
```

```{r}
ggplot(data = datasetfull, aes(x = region, y = charges)) + geom_point()
```

#Setting indicator variable
```{r}
#sex1 = ifelse(sex=="female", 1, 0)
#smoker1 = ifelse(smoker =="yes", 1, 0)
region = as.factor(rep(c("southeast", "southwest", "northeast", "northwest"),nrow(datasetfull)))
region1 = ifelse(region == "southeast", 1, 0)
region2 = ifelse(region == "southwest", 1, 0)
region3 = ifelse(region == "northeast", 1, 0)
region4 = ifelse(region == "northwest", 1, 0)

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

